[package]
name = "backend"
version = "0.1.0"
authors = ["Troy Karan Harrison <NoxPardalis@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]
corgis = { path = "corgis", version = "*" }
rocket = "0.4.0"
rocket_contrib = "0.4.0"
