edition = "2018"
format_doc_comments = true
format_strings = true
merge_imports = true
normalize_comments=true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
version = "Two"
wrap_comments = false