[package]
name = "rocket_contrib_local"
version = "0.1.0"
authors = ["Troy Karan Harrison <NoxPardalis@protonmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
rustic_hal = "0.2.0"
serde = "1.0.89"
