[package]
name = "corgis_dataset"
version = "0.1.0"
authors = ["Troy Karan Harrison <NoxPardalis@protonmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
